repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2 # Specify the desired Ruff version
    hooks:
      - id: ruff-check # Run the linter
        args: [--fix] # Optional: automatically fix linting issues
      - id: ruff-format # Run the formatter
